#!/bin/bash
g++  -fsigned-char -w -O2 -pipe -fmessage-length=0 -Wp,-D_FORTIFY_SOURCE=2 -ftree-vectorize -ffunction-sections -fno-stack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fpermissive -m64 -DEVENT_DEBUG -DDEBUG_FILE_LINE -DB_DEBUG -DUI_DEBUG -DCONVERT_LINUX -DX64_BASED_SYSTEM -fpic  -fexceptions -frtti -std=c++11 -I. -I./.. -I./../../../3rd_party/java/include -I./../../../3rd_party/java/include/linux  -c com_infraware_office_evengine_EvNative.cpp -o ../../build/linux/out/CONVERT_LINUX/centos/Debug/x64/EngineSO/com_infraware_office_evengine_EvNative.o
g++  -fsigned-char -w -O2 -pipe -fmessage-length=0 -Wp,-D_FORTIFY_SOURCE=2 -ftree-vectorize -ffunction-sections -fno-stack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fpermissive -m64 -DEVENT_DEBUG -DDEBUG_FILE_LINE -DB_DEBUG -DUI_DEBUG -DCONVERT_LINUX -DX64_BASED_SYSTEM -fpic  -fexceptions -frtti -std=c++11 -I. -I./.. -I./../../../3rd_party/java/include -I./../../../3rd_party/java/include/linux  -c debugJni.cpp -o ../../build/linux/out/CONVERT_LINUX/centos/Debug/x64/EngineSO/debugJni.o
g++  -fsigned-char -w -O2 -pipe -fmessage-length=0 -Wp,-D_FORTIFY_SOURCE=2 -ftree-vectorize -ffunction-sections -fno-stack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fpermissive -m64 -DEVENT_DEBUG -DDEBUG_FILE_LINE -DB_DEBUG -DUI_DEBUG -DCONVERT_LINUX -DX64_BASED_SYSTEM -fpic  -fexceptions -frtti -std=c++11 -I. -I./.. -I./../../../3rd_party/java/include -I./../../../3rd_party/java/include/linux  -c implementNative.cpp -o ../../build/linux/out/CONVERT_LINUX/centos/Debug/x64/EngineSO/implementNative.o
g++  -fsigned-char -w -O2 -pipe -fmessage-length=0 -Wp,-D_FORTIFY_SOURCE=2 -ftree-vectorize -ffunction-sections -fno-stack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fpermissive -m64 -DEVENT_DEBUG -DDEBUG_FILE_LINE -DB_DEBUG -DUI_DEBUG -DCONVERT_LINUX -DX64_BASED_SYSTEM -fpic  -fexceptions -frtti -std=c++11 -I. -I./.. -I./../../../3rd_party/java/include -I./../../../3rd_party/java/include/linux  -c native.cpp -o ../../build/linux/out/CONVERT_LINUX/centos/Debug/x64/EngineSO/native.o
g++  -fsigned-char -w -O2 -pipe -fmessage-length=0 -Wp,-D_FORTIFY_SOURCE=2 -ftree-vectorize -ffunction-sections -fno-stack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fpermissive -m64 -DEVENT_DEBUG -DDEBUG_FILE_LINE -DB_DEBUG -DUI_DEBUG -DCONVERT_LINUX -DX64_BASED_SYSTEM -fpic  -fexceptions -frtti -std=c++11 -I. -I./.. -I./../../../3rd_party/java/include -I./../../../3rd_party/java/include/linux  -c nativeCallback.cpp -o ../../build/linux/out/CONVERT_LINUX/centos/Debug/x64/EngineSO/nativeCallback.o
g++  -fsigned-char -w -O2 -pipe -fmessage-length=0 -Wp,-D_FORTIFY_SOURCE=2 -ftree-vectorize -ffunction-sections -fno-stack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fpermissive -m64 -DEVENT_DEBUG -DDEBUG_FILE_LINE -DB_DEBUG -DUI_DEBUG -DCONVERT_LINUX -DX64_BASED_SYSTEM -fpic  -fexceptions -frtti -std=c++11 -I. -I./.. -I./../../../3rd_party/java/include -I./../../../3rd_party/java/include/linux  -c loadUcnv.cpp -o ../../build/linux/out/CONVERT_LINUX/centos/Debug/x64/EngineSO/loadUcnv.o
g++  -fsigned-char -w -O2 -pipe -fmessage-length=0 -Wp,-D_FORTIFY_SOURCE=2 -ftree-vectorize -ffunction-sections -fno-stack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fpermissive -m64 -DEVENT_DEBUG -DDEBUG_FILE_LINE -DB_DEBUG -DUI_DEBUG -DCONVERT_LINUX -DX64_BASED_SYSTEM -fpic  -fexceptions -frtti -std=c++11 -I. -I./.. -I./../../../3rd_party/java/include -I./../../../3rd_party/java/include/linux  -c nativeStringUtil.cpp -o ../../build/linux/out/CONVERT_LINUX/centos/Debug/x64/EngineSO/nativeStringUtil.o
g++  -fsigned-char -w -O2 -pipe -fmessage-length=0 -Wp,-D_FORTIFY_SOURCE=2 -ftree-vectorize -ffunction-sections -fno-stack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fpermissive -m64 -DEVENT_DEBUG -DDEBUG_FILE_LINE -DB_DEBUG -DUI_DEBUG -DCONVERT_LINUX -DX64_BASED_SYSTEM -fpic  -fexceptions -frtti -std=c++11 -I. -I./.. -I./../../../3rd_party/java/include -I./../../../3rd_party/java/include/linux  -c ./License/licenseChecker.cpp -o ../../build/linux/out/CONVERT_LINUX/centos/Debug/x64/EngineSO/licenseChecker.o
g++  ../../build/linux/out/CONVERT_LINUX/centos/Debug/x64/EngineSO/com_infraware_office_evengine_EvNative.o ../../build/linux/out/CONVERT_LINUX/centos/Debug/x64/EngineSO/debugJni.o ../../build/linux/out/CONVERT_LINUX/centos/Debug/x64/EngineSO/implementNative.o ../../build/linux/out/CONVERT_LINUX/centos/Debug/x64/EngineSO/native.o ../../build/linux/out/CONVERT_LINUX/centos/Debug/x64/EngineSO/nativeCallback.o ../../build/linux/out/CONVERT_LINUX/centos/Debug/x64/EngineSO/loadUcnv.o ../../build/linux/out/CONVERT_LINUX/centos/Debug/x64/EngineSO/nativeStringUtil.o ../../build/linux/out/CONVERT_LINUX/centos/Debug/x64/EngineSO/licenseChecker.o  ./lib/x64/libPOEngine.a ./lib/x64/common.a ./lib/x64/i18n.a ./lib/x64/stubdata.a ./lib/x64/png.a ./lib/x64/zlib.a ./lib/x64/jpeg.a ./lib/x64/lcms2.a ./lib/x64/harfbuzz.a ./lib/x64/eot.a ./lib/x64/internal_skia.a ./lib/x64/freetype2.a ./lib/x64/jpegxr.a ./lib/x64/tiff.a ./lib/x64/openjpeg.a ./lib/x64/pugixml.a ./lib/x64/expat.a ./lib/x64/lcms2.a -Wl,-soname,libpolarisoffice8.so -shared  -lc -lm -lpthread -ldl -lrt  -o ../../build/linux/out/CONVERT_LINUX/centos/Debug/x64/EngineSO/libpolarisoffice8.so	
strip  ../../build/linux/out/CONVERT_LINUX/centos/Debug/x64/EngineSO/libpolarisoffice8.so
